var express = require('express');
var app = express();

var port = 8000; 

app.listen(port, function(err, res){
  if(err){
    console.log('server error');
  }
  else {
    console.log('server started on port 8000');
  }
});
// node app
// node app.js
// self written rather than autogenerated (no npm start)
// nodemon is a new npm start